name: DailyBuzzTestActions

on:
    pull_request:
        branches:
            - Test

jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with: 
          mongodb-version: 8.0
      

      # Install dependencies
      - name: 🧰 Install Deps
        run: npm install

      # Run build
      - name: Run Build
        run: npm run build